### ISSUE TITLE
split up main.py according to classic RL parts

### ISSUE THREAD

**Issue by iejMac** [aogara-ds/hoodwinked-website#2]
player.py or agent.py is fine, maybe agent.py since an agent can be a player or a bot and then you just implement different ways of controlling agents (random, human, GPT-3)

environment.py - this is your Game class

**Comment by aogara-ds** [comment]
Nice, done here: https://github.com/aogara-ds/hoodwinked/commit/36a3b1f026e4fabc24438786f1aefa058ed373d3
